server:
  port: 7654

spring:
  application:
    name: ergo-gateway-service

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

cloud:
  gateway:
    discovery:
      enabled: true
      locator:
        enabled: true
        lower-case-service-id: true

    routes:
      - id: ergo-user-management-service
        uri: http://localhost:9187/ergoBuddy/users
        predicates:
          - Path=/ergoBuddy/users/**
