server:
  port: 7654

spring:
  application:
    name: ergoGateWayService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

cloud:
  gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: ergoUserManagementService
        uri: lb://ergoUserManagementService
        predicates:
          - Path=/ergoBuddy/users/** 
        filters:
          - StripPrefix=1

