server:
  port: 8761

spring:
  application:
    name: ergo-eureka-service
    
eureka:
  instance:
    hostname : localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false  